---
title: TypeScript try-catch 에서의 Error 처리하기
description: unknown인 Error을 핸들링해봐요
date: 2024-02-19
thumbnail: /blogImages/2024/2024_02/2024_02_19/2024_02_19_(1).webp
category:
  - TypeScript
---

## 서론

여느때와 같이 빈둥거리다가 코딩을 하고있었는데, **try-catch**문에서 계속 빨간줄을 그어서 뭔가 하고 봤더니 TS Error가 발생하더라구요
catch에서 사용하는 Error에 대한 타입 에러였는데, 해당 문제에 대해서 학습한 내용을 몇 자 적어보려고 합니다.

## try-catch에서 Error는 어떤 타입인가?

TS 4.4버전 이전까지 TS에서는 try/catch 에서의 Error를 **any**타입으로 지정하고 있었습니다만, 4.4버전 이후부터는 **unknown**타입으로 변경되었습니다.
따라서 제가 다음과 같이 하려고 했을때 지속적으로 에러를 발생시킨 것 이었습니다.

```ts showLineNumbers {11}
export const registerUser = createAsyncThunk(
  'user/registerUser',
  async (body: RequestBody, thunkAPI) => {
    try {
      const response = await axiosInstance.post(`/users/register`, body)

      return response.data
    } catch (error) {
      console.log(error)

      return thunkAPI.rejectWithValue(error.response.data)
    }
  }
)
```

타입이 **unknown**이기때문에, **error.response**에 접근하려고 하면 타입에러가 발생하는것입니다.

여기까지 분석이 완료되었다면, 우리는 문제의 본질을 파악할 수 있습니다. 바로, **unknown타입을 핸들링하기** 라는걸요.
따라서, 이 unknown 타입을 핸들링하는 방법에 대해서 알아보겠습니다 :)

### any타입 사용하기

```ts showLineNumbers {11}
export const registerUser = createAsyncThunk(
  'user/registerUser',
  async (body: RequestBody, thunkAPI) => {
    try {
      const response = await axiosInstance.post(`/users/register`, body)

      return response.data
    } catch (error: any) {
      console.log(error)

      return thunkAPI.rejectWithValue(error.response.data)
    }
  }
)
```

가장 간단한 방법입니다, **any** 타입을 사용함으로써 해당 에러를 방지할 수 있습니다.. 만
타입스크립트를 사용하면서 **any** 타입을 도배한다는 건, 타입스크립트를 사용하는분들이라면 반드시 **지양**해야할 행동임을 알고계실거라고 생각합니다.

또한 **any**타입으로 도배한다면 **Eslint**에서도 지속적으로 경고창을 띄우고, 이를 피하기위해 해당 경고까지 무시해버린다면 사실상 **TS**와 **Eslint**를 사용하지 않는것과 마찬가지겠죠?

그러니 다음 방법으로 넘어가봅시다.

### 타입을 단언 하기

```ts showLineNumbers {9}
export const registerUser = createAsyncThunk(
  'user/registerUser',
  async (body: RequestBody, thunkAPI) => {
    try {
      const response = await axiosInstance.post(`/users/register`, body)

      return response.data
    } catch (error) {
      const customError = error as CustomError
      console.log(error)

      return thunkAPI.rejectWithValue(error.response.data)
    }
  }
)
```

CustomError라는 커스텀 타입(인터페이스)를 생성하여 타입 단언을 하는 방법이 있을 수 있겠습니다.
저같은경우는 **error.response**만 사용할 것이기 때문에 타입을 작성한다면 다음과 같이 작성할 것 같네요

```ts showLineNumbers
export default class CustomError extends Error {
  response?: {
    data: unknown
    status: number
    headers: string
  }
}
```

하지만, 이 선택지 역시나 **any**보단 낫겠지만 타입을 **단언**한다는 점에서 다른 좋은 대안이 있다면 **지양**하는것이 좋습니다.

이번에도 다음 방법으로 넘어가봅시다.

### 타입 가드를 사용 하기

- [[TypeScript Deep Dive] 타입 가드](https://radlohead.gitbook.io/typescript-deep-dive/type-system/typeguard)

추천되는 방법 중 하나로는 **typeof**나 **instanceof**를 사용하여 타입가드 하는 방법이 있습니다.

```ts showLineNumbers
export const registerUser = createAsyncThunk(
  'user/registerUser',
  async (body: RequestBody, thunkAPI) => {
    try {
      const response = await axiosInstance.post(`/users/register`, body)

      return response.data
    } catch (error) {
      console.log(error)

      if (error instanceof CustomError) {
        return thunkAPI.rejectWithValue(error.response?.data)
      }
    }
  }
)
```

```ts showLineNumbers
export default class CustomError extends Error {
  response?: {
    data: unknown
    status: number
    headers: string
  }
}
```

커스텀 에러 클래스를 정의한 뒤, **instanceof**를 사용하여 타입가드를 했습니다.
이렇게 타입가드를 사용하면 **any**도, **타입 단언**도 모두 사용하지 않고 **unknown**타입을 핸들링할 수 있습니다.

다만, **axios**의 경우 커스텀 클래스를 사용하지 않고도 편하게 해당 문제를 해결할 수 있습니다.

### axios.isAxiosError()

```ts showLineNumbers {11}
export const registerUser = createAsyncThunk(
  'user/registerUser',
  async (body: RequestBody, thunkAPI) => {
    try {
      const response = await axiosInstance.post(`/users/register`, body)

      return response.data
    } catch (error) {
      console.log(error)

      if (isAxiosError(error)) {
        return thunkAPI.rejectWithValue(error.response?.data)
      }
    }
  }
)
```

- [[Axios] TypeScript](https://github.com/axios/axios/tree/main#typescript)

**Axios** 공식문서에서는 **axios error**의 타입 가드를 위해 **axios.isAxiosError()** 를 제공합니다.
해당 함수 사용시 axios에서는 간단하게 타입 가드를 할 수 있습니다!

## 참고

- [[Inpa Dev] 타입스크립트 커스텀 Error 처리하기](https://inpa.tistory.com/entry/TS-%F0%9F%93%98-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%BB%A4%EC%8A%A4%ED%85%80-Error-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)
- [[frykim] 타입스크립트에서 Axios Error 처리하기](https://gxxrxn.github.io/axios-error-type-guard/)
